//updateme <-- Remove this line when editing
thisProcess.nowExecutingPath.debug("TODO");

Cell({

	~template[\buffer] = Fdef(\resolveAssets).value((
		 'melodi_under_50_hz_cats_only': "081 melodi under 50 hz/melodi under 50 hz_cats only.wav",
		 '081_melodi_under_50_hz_katrine': "081 melodi under 50 hz/081_melodi under 50 hz_katrine.wav",
		 '081_melodi_under_50_hz': "081 melodi under 50 hz/081_melodi under 50 hz.wav" 
	));

}, \disk).name_(PathName(thisProcess.nowExecutingPath).folderName)
