//updateme <-- Remove this line when editing
thisProcess.nowExecutingPath.debug("TODO");

Cell({

	~template[\buffer] = Fdef(\resolveAssets).value((
		 '080_cittra,
		_andetag_andetag': "080 cittra,
		 andetag/080 cittra,
		 andetag_andetag.wav",
		 '080_cittra,
		_andetag': "080 cittra,
		 andetag/080 cittra,
		 andetag.wav" 
	));

}, \disk).name_(PathName(thisProcess.nowExecutingPath).folderName)
