thisProcess.nowExecutingPath.debug("TODO");

Cell({

	~template[\buffer] = Fdef(\resolveAssets).value((
		 //'098_spelglädje_för_ostämd_gitarr_loop': "098 spelglädje för ostämd gitarr/098 spelglädje för ostämd gitarr_loop.wav",
		 '098_spelgladje_för_ostämd_gitarr': "098 spelglädje för ostämd gitarr/098 spelglädje för ostämd gitarr.wav" 
	));

}, \disk).name_(PathName(thisProcess.nowExecutingPath).folderName)
