//updateme <-- Remove this line when editing
thisProcess.nowExecutingPath.debug("TODO");

Cell({

	~template[\buffer] = Fdef(\resolveAssets).value((
		 '093_dålig_täckning_loop': "093 dålig täckning/093 dålig täckning_loop.wav",
		 '093_dålig_täckning_inferno_loop': "093 dålig täckning/093 dålig täckning_inferno loop.wav" 
	));

}, \disk).name_(PathName(thisProcess.nowExecutingPath).folderName)
